name: stat214
channels:
  - defaults
dependencies:
  - python
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - jupyterlab
      # ---- add for this project ----
      - plotly
      - kaleido
      - statsmodels
      - pyarrow
      - nbclient
      - ipykernel
      - notebook
      - ruff